services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data

