{
 "title": "Evidently Dashboard",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Median Fare Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT median_fare_amount AS \"value\", \"timestamp\" AS \"time\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_missing_val AS \"value\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", num_drifted_colums AS \"value\" FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}