services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      # - TEST_RUN=True
      # - RUN_ID=None
      - AWS_DEFAULT_REGION=us-east-1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4567:4567"
    environment:
      - SERVICES=kinesis
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
#     volumes:
#       - "localstack_data:/tmp/localstack/data"

# volumes:
#   localstack_data:
    